### ISSUE TITLE
Uwagi do prototypu

### ISSUE THREAD

**Issue by gagop** [Ga1ahad/BackendPJA#12]
Prośba, żeby trzymać spójną typografią:
- albo wszystkie tytuły wielką literą, albo każde słowo z wielkiej litery itd.

Na poprzednim ekranie "SZAFA" była duzymi literami, więc trzymałbym się tego.

Pytanie: gdzie w dodawaniu ubrania pojawia się ladowanie tagów z zewn API z pomocą AI opisującego zdjecia? 
Gdzie mozna oznaczyc Body Part? (jest cos takiego w bazie danych).
Kopiujcie poprzedni ekran, tak aby były takie same. Niech prototypu beda spójne.

**Comment by Ga1ahad** [comment]
Chciałbym aby po dodaniu zdjęcia ubrania pojawiały się zasugerowane tagi z zewn API.

**Comment by Ga1ahad** [comment]
Po przeanalizowaniu body part wydaje się zbędny.
